export const GET_BANNER_IMAGE_REQUEST = "GET_BANNER_IMAGE_REQUEST"
export const GET_BANNER_IMAGE_SUCCESS = "GET_BANNER_IMAGE_SUCCESS"
export const GET_BANNER_IMAGE_FAILURE = "GET_BANNER_IMAGE_FAILURE"


export const ADD_BANNER_IMAGE_REQUEST = "ADD_BANNER_IMAGE_REQUEST"
export const ADD_BANNER_IMAGE_SUCCESS = "ADD_BANNER_IMAGE_SUCCESS"
export const ADD_BANNER_IMAGE_FAILURE = "ADD_BANNER_IMAGE_FAILURE"

export const DELETE_BANNER_IMAGE_REQUEST = "DELETE_BANNER_IMAGE_REQUEST"
export const DELETE_BANNER_IMAGE_SUCCESS = "DELETE_BANNER_IMAGE_SUCCESS"
export const DELETE_BANNER_IMAGE_FAILURE = "DELETE_BANNER_IMAGE_FAILURE"
